### ISSUE TITLE
searching for " " or hitting backspace puts Lesotho at the top of the list

### ISSUE THREAD

**Issue by roryok** [jamieholst/selectToAutocomplete#36] opened 2012-04-16 09:23 UTC
If you remove Lesotho, this changes to the next down the list, Liberia. Removing all the L countries puts Kyrgyzstan at the top. Something is seriously borked with the sorting.

**Comment by jaystarkey** [comment] 2012-04-30 03:26
Confirmed. Also, A entry is moved into the L's.  I'm using Chrome and suspect that everyone with this issue is also using Chrome. The bug report by @kopymark is surely the same error.

**Comment by myblake** [comment] 2012-12-05 00:32
I'm seeing a similar issue though actually a bit more generically, it appears to be swapping the first element with the (n/2)th element.

**Comment by dizyart** [comment] 2013-01-06 03:26
I have also tested and confirmed the n/2 rule. 

After that, the list continues in alphabetical order with AN EXCEPTION that it puts the SECOND element (Åland Islands in my case) in the place of the n/2th element.

So it shows:
Lesotho
Afganistan
.... _alphabetical order_ ...
Lebanon
Åland Islands
Liberia
....

I have tried removing Åland Islands, to check if the unicode character might be the problem, but it's not.

In addition, it sometimes seems to add an empty list element below the first one in the drop-down, but I cannot replicate it again.. :/ Will get back if I do.

**Comment by marcroberts** [comment] 2013-07-12 09:53
There is a bug report files against V8 for this, but due to the fact that the spec says the sort algorithm need not be stable is is marked as 'WorkingAsIntended' https://code.google.com/p/v8/issues/detail?id=90

I've fixed this for our use case by falling back to sorting alphabetically if the relevancy scores are identical

**Comment by jamieholst** [comment] 2014-08-12 10:17
Fixed, courtesy of macroberts pull request.

Cheers!

**Closed as completed by jamieholst** 2014-08-12 10:17 UTC
