### ISSUE TITLE
Non-intuitive sorting logic for 'Ireland'

### ISSUE THREAD

**Issue by UserJourneys** [jamieholst/selectToAutocomplete#21] opened 2011-11-25 12:03 UTC
When the user types 'Ireland' the results come back in this order:
- United Kingdom
- Ireland

Since the Republic of Ireland, which is usually referred to as 'Ireland', is not part of the United Kingdom, this sorting logic is not intuitive, i.e. when the user types Ireland, they most likely do not mean the United Kingdom. 

I would expect to see the following results, in this order:
- Ireland
- United Kingdom

Northern Ireland is part of the UK, so it does make sense to leave the United Kingdom in the list of results, but not as the first item.

**Comment by jamieholst** [comment] 2011-11-27 11:49
True. It's a matter of the relevancy booster being much higher on UK. 

The issue is already [being discussed here](https://github.com/JamieAppleseed/selectToAutocomplete/issues/11) so I'm closing this issue.

**Closed as completed by jamieholst** 2011-11-27 11:49 UTC
